package me.luisortiz.hellohibernate;

// Generated 30-mar-2014 23:35:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Peliculas generated by hbm2java
 */
@Entity
@Table(name = "peliculas", catalog = "hellohibernate")
public class Peliculas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idPeliculas;
	private String pelicula;
	private int clasificacion;
	private Set<Reservas> reservases = new HashSet<Reservas>(0);

	public Peliculas() {
	}

	public Peliculas(int idPeliculas, String pelicula, int clasificacion) {
		this.idPeliculas = idPeliculas;
		this.pelicula = pelicula;
		this.clasificacion = clasificacion;
	}

	public Peliculas(int idPeliculas, String pelicula, int clasificacion,
			Set<Reservas> reservases) {
		this.idPeliculas = idPeliculas;
		this.pelicula = pelicula;
		this.clasificacion = clasificacion;
		this.reservases = reservases;
	}

	@Id
	@Column(name = "idPeliculas", unique = true, nullable = false)
	public int getIdPeliculas() {
		return this.idPeliculas;
	}

	public void setIdPeliculas(int idPeliculas) {
		this.idPeliculas = idPeliculas;
	}

	@Column(name = "pelicula", nullable = false, length = 45)
	public String getPelicula() {
		return this.pelicula;
	}

	public void setPelicula(String pelicula) {
		this.pelicula = pelicula;
	}

	@Column(name = "clasificacion", nullable = false)
	public int getClasificacion() {
		return this.clasificacion;
	}

	public void setClasificacion(int clasificacion) {
		this.clasificacion = clasificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pelicula")
	public Set<Reservas> getReservases() {
		return this.reservases;
	}

	public void setReservases(Set<Reservas> reservases) {
		this.reservases = reservases;
	}

}
