package me.luisortiz.hellohibernate;

// Generated 30-mar-2014 23:35:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * Reservas generated by hbm2java
 */
@Entity
@Table(name = "reservas", catalog = "hellohibernate")
public class Reservas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idReservas;
	private Usuarios usuarios;
	private Peliculas peliculas;

	public Reservas() {
	}

	public Reservas(int idReservas, Usuarios usuarios, Peliculas peliculas) {
		this.idReservas = idReservas;
		this.usuarios = usuarios;
		this.peliculas = peliculas;
	}

	@Id
	@Column(name = "idReservas", unique = true, nullable = false)
	public int getIdReservas() {
		return this.idReservas;
	}

	public void setIdReservas(int idReservas) {
		this.idReservas = idReservas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario", nullable = false)
	public Usuarios getUsuario() {
		return this.usuarios;
	}

	public void setUsuario(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pelicula", nullable = false)
	public Peliculas getPelicula() {
		return this.peliculas;
	}

	public void setPelicula(Peliculas peliculas) {
		this.peliculas = peliculas;
	}

}
