package me.luisortiz.hellohibernate;

// Generated 30-mar-2014 23:35:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", catalog = "hellohibernate")
public class Usuarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3685067070974756908L;
	private int idUsuario;
	private String nombre;
	private int edad;
	private Set<Reservas> reservases = new HashSet<Reservas>(0);

	public Usuarios() {
	}

	public Usuarios(int idUsuario, String nombre, int edad) {
		this.idUsuario = idUsuario;
		this.nombre = nombre;
		this.edad = edad;
	}

	public Usuarios(int idUsuario, String nombre, int edad, Set<Reservas> reservases) {
		this.idUsuario = idUsuario;
		this.nombre = nombre;
		this.edad = edad;
		this.reservases = reservases;
	}

	@Id
	@Column(name = "idUsuario", unique = true, nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "edad", nullable = false)
	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Reservas> getReservases() {
		return this.reservases;
	}

	public void setReservases(Set<Reservas> reservases) {
		this.reservases = reservases;
	}

}
